sudo: required
language: ruby
services: docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO="dimmsd/ubuntu-base"
  - secure: D5NWV2DfoF/nBfcjlVMuLYdw+4bh9DQPjvYBsOKrPvR9oF5uEjd2sCm5wL/+AyDbBrYaidQzuAHB+l1goNVaPeCVfRskqzqbQAJ28YtiQS/B3bJvQ99fbLh3MUhJUqSpFGeGjCxNjdx2OquKK6HsKctIVz8EKpkG+wCxvHxLnjGMXo2fbB8kfHv5uN4qV4WMuGWX82U+UBWP1zQKTpFZkZs/6hjl4Lyymi01M31TRbMuAexHlEAv8FqRf6b6F02pzwtWK2qfeKnEPKXlG7lIJDwk6l8QYK/IiCzP/Nd64oLWfhBKE3jMELXO3VetO0lgX3Z75eVi93ceOpRmaNsEvovbkCK9zyGJkDzayEK6vsIc1A5KH4hzbFFYDq0TuwuRSr7Gl8SOFu1OH608DGEoSaZ8Kp21Su+eBN/vnLo5i0knzE9HxQDNsd91dC4nMIJ7fpMJuLdtJiK5XClEKehinv6a6wK2XNoGOsWrAf2hKYHVgIiel/BcXc8VDD4hIe0Cq4tyw+CZn4NlcBjukD4Pkfw3/SkdYEJIk/aLH0/tYdg5xiStWCuCdkpHeydk9EUGHNPJro3Y+L7wCLEymUoUJ2ON/FzH753AJGPQ17x8zTC+Ps2KdX1YwTqFpormqEyhoHYiPx9BA7LbtiTn+im6Tz3J5PvEIMHTd3sWvFYuhl8=
  - secure: KoIWIRwOKEil0pOl2tpwtQEOBTOT8C/nhslp3W7Pa1juY0ig559FwyelFLaGU4Ljy3C3zC6ek/Kj9xz1tqmjNoGSQ6f4ori3RqJmulDSmt599W6KNL98If9It9YgMQy3xcEaMtcu6J/0U6lPjKzQGR2bD0+/sY0bb7NRA33xwBDAT8wsjGLPMBJgTHWcVNtZ1mHEeRfH7KC3zH3sEc+7MJrUjBs1feaKBFOmkeN5lSp+FcW6HM+tj7VnzMbiFUkvd+tPnl9DvmAfp44YiAt8rHPh8bDrsAZrBAZSA1qmHPEA6VaDF8shRSlSX/3p0AHgbvb+Dc78ZLwY+pe65IyrzIkzlJcD40mp+KFxOpcL1cwPx0DifISF3Yip06oAM1oAbdR2L2FURJERcNgKFvGnYb4N6BSJuOCA8pgmDBXRiC/wlaDAQwv/3RqCgRlX+dQIo23puEZxmnDSivXsoiNCj8RJFevXs7M3hqPqQNdHVyh1mZSGoFvsng6WY25V3Tr0s/dwW3ZbX15DUCXxb+j7zp0j1dwySBahT0NH7gxr1oZPhidbxkwZYMNfbWABeMrfer5bmY4Q/nsIBEydfu+Teg4DYoWdX/17kML4IZQyPPson+OgVozH1SGUmvqfZeCvEiaoX55C9LkZh/I8y+NUF7+bqyxcUA52iukhvmExU1A=
  - secure: geDTIqJ6Rm1lPJWmRHD+TH+yVXCnLzFg/e/4Rn3kf+i0WIr6WIsUJ0AqZI5PG5PKR29UONCVwcXNvBKUAC3PoW/OWLU+gd9GpTT6gxsotkWhOOBjMunex1jGg00U2nyN+Lr7DqbcXkm/1x1bPk0tsqnyMEcWaX1+J7F7+700r+cnkFHLZRWOjMYb6J8k+89WpoXGzLEQGKEMQ/5EySfKrc/Pl7VhWnYP0rom5Jnw8E4/S68qAbA90AitUhmtuITATarBVOFk4FTGyvIjeEAeBFivafwjChLGZrpj1ctWAJG/kWyYFxRc/RKO8tumkkvSICgAqLsN/ClWi3YzRlO9HqYtlmpAv07kivDZYB4Cl0fquvWaUzYTKps/9IO/u+lNvmAc78o1FEcBY5U8a8A1nP4ZHH5HIQDgSxNj+O9MYuRBPIymjIo4MYIP6KU5u0xzppN1OB506leSX4FAhrz9GjI37Gtd4qcuCOx++prIbQWh7O3hsi9/YAZLQC8PMtUiw3XVDhqWBPtEJEByCEl7rUoBaKLlepL3VN4/0F2DZw83jTKqdroNOhuNy9+RGclJvRCDZChRF2lvmHvevOX6H3H0GMAIv66oD/OXBaanjiPPXwFEWluJ3ikYuQF4bikb/NDRLm5Y50aIY+U1StUxsxcDCRJ/BRpaVDWQChvSjbA=
  matrix:
  - UBUNTU_VERSION=16.04
  - UBUNTU_VERSION=18.04
  - UBUNTU_VERSION=20.04
before_install:
- sudo apt update -y
- sudo apt install --only-upgrade docker-ce -y
- sudo pip install docker-squash
- docker build --build-arg UBUNTU_VERSION=$UBUNTU_VERSION -t $REPO:$COMMIT .
- sudo docker-squash -t $REPO:$COMMIT-squashed $REPO:$COMMIT --verbose
script:
- docker images
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=$UBUNTU_VERSION
- docker tag $REPO:$COMMIT-squashed $REPO:$TAG
- docker push $REPO:$TAG
